# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:  十八画
subtitle: 记录生活&工作
name:  
email: jin_jian@126.com
description: 记下来
keywords: 个人博客
encoding: "utf-8"
favicon: favicon.ico

repository: iveskim/iveskim.github.io
github_url: https://github.com/iveskim
url: https://iveskim.github.io
enforce_ssl: 

## Gem
plugins:
  - jekyll-paginate
  - jekyll-geo-pattern
  - rouge
  - kramdown
  - jekyll-github-metadata

# Build settings
markdown: kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

source:      .
destination: ./_site

quiet:    false
defaults: []

kramdown:
  input: GFM
  enable_coderay: true
  syntax_highlighter: rouge

syntax_highlighter_opts:
   coderay_line_numbers:  nil

# Pagination
paginate: 12
paginate_path: 'page:num'

# Navigation. main menu list
navs:

  -
    href: /archives.html
    label: Archives
    target: _self

  - href: /about.html
    label: 关于
    target: _self



# labels. my blog key words
labels:

  -
    href:
    label:
    target:


# selected articles
classes:

  -
    href: /other/2020/01/16/markdown.html
    name: Markdown
    describe: 相关使用和说明

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# Sidebar to show popular repo
side_bar_repo_limit: 6 # Number of repos to show

# Google Analytics
# analytics :
# provider : google
#   google :
#     tracking_id : ''  # ex. UA-72165600-X


